version: "3.9"

services:
  fantastic:
    build: .
    image: fantastic:${TAG}
    container_name: fantastic
    network_mode: host
    pull_policy: never

networks:
  default: 
    external: true
    name: host
